### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by dio007** [CampaignChain/campaignchain-ce#19]
<img width="732" alt="screen shot 2016-01-18 at 8 44 39 am" src="https://cloud.githubusercontent.com/assets/16250395/12394168/d921670c-bdbf-11e5-9cd4-3f35359767cf.png">
 can somebody help me!!!

**Comment by rogamoore** [comment]
Looks like you don't have npm installed. Please check step 3 in the installation guide :)
https://github.com/CampaignChain/campaignchain-ce/blob/master/README.md

**Comment by dio007** [comment]
<img width="957" alt="screen shot 2016-01-18 at 10 07 36 am" src="https://cloud.githubusercontent.com/assets/16250395/12396129/60e30640-bdcb-11e5-9148-13c5d484f4c7.png">
i change the timezone on php.ini and install/enable intl extension, but still not working!

**Comment by dio007** [comment]
<img width="506" alt="screen shot 2016-01-18 at 10 52 31 am" src="https://cloud.githubusercontent.com/assets/16250395/12397240/a4693852-bdd1-11e5-9517-d4691617971b.png">
<img width="767" alt="screen shot 2016-01-18 at 10 51 26 am" src="https://cloud.githubusercontent.com/assets/16250395/12397239/a465e454-bdd1-11e5-9a6e-86acccd40af1.png">
here some screenshots  of the changes!

**Comment by rogamoore** [comment]
Did you change the php config at the path given in your error message (not the CLI config) and did you restart your web server?

**Comment by dio007** [comment]
<img width="877" alt="screen shot 2016-01-18 at 11 44 03 am" src="https://cloud.githubusercontent.com/assets/16250395/12398377/05ebfb94-bdd9-11e5-863f-135cd876088f.png">

I restart the web server, and now is only the timezone error!  i follow the instructions to change the time, please help

**Comment by rogamoore** [comment]
Did you remove the semicolon?

**Comment by groganz** [comment]
CampaignChain will always set the timezone to UTC on runtime. Hence it does
not matter which timezone you specify in php.ini.

rogamoore <notifications@github.com> schrieb am Mo., 18. Jan. 2016 18:49:

**Comment by rogamoore** [comment]
@groganz Symfony requires that a timezone is set in the PHP.ini. And I think CampaignChain is also testing the Symfony requirements on the first step of the install wizard.
http://symfony.com/doc/current/reference/requirements.html

**Comment by groganz** [comment]
True, just saying so that @dio007 knows.

rogamoore <notifications@github.com> schrieb am Mo., 18. Jan. 2016 19:21:

**Comment by rogamoore** [comment]
I know :)
I think there is a misunderstanding, because the missing timezone setting is the reason why he cannot continue the install wizard and finish the CampaignChain installation, please correct me if I'm wrong :)

**Comment by groganz** [comment]
Indeed, that's what it looks like :)

rogamoore <notifications@github.com> schrieb am Mo., 18. Jan. 2016 23:35:

**Comment by dio007** [comment]
thanks guys, for your help!! now is working!!

**Comment by rogamoore** [comment]
great :)
