### ISSUE TITLE
Error when running "php app/console cache:clear --env=prod --no-debug"

### ISSUE THREAD

**Issue by tipcircle** [CampaignChain/campaignchain-ce#22]
I'm getting this error when I run php app/console cache:clear --env=prod --no-debug

[Symfony\Component\Config\Exception\FileLoaderLoadException]                                           
  [Semantical Error] The annotation "@FOS\RestBundle\Controller\Annotations\GET" in method CampaignChai  
  n\CoreBundle\Controller\REST\PackageController::getVendorsMetaAction() does not exist, or could not b  
  e auto-loaded in CampaignChain\CoreBundle\Controller\REST\PackageController (which is being imported   
  from "/var/www/campaignchain/vendor/campaignchain/core/Resources/config/routing_rest.yml").  

[Doctrine\Common\Annotations\AnnotationException]                                                      
  [Semantical Error] The annotation "@FOS\RestBundle\Controller\Annotations\GET" in method CampaignChai  
  n\CoreBundle\Controller\REST\PackageController::getVendorsMetaAction() does not exist, or could not b  
  e auto-loaded.

**Comment by rogamoore** [comment]
Hi tipcircle,

how did you install CampaignChain and what are you trying to do? Are you using the latest version?

**Comment by tipcircle** [comment]
Hello, I installed it according to the steps here: https://github.com/CampaignChain/campaignchain-ce/blob/master/README.md

I get this error on step 6

**Comment by tipcircle** [comment]
Version 1.0.0-beta.3

**Comment by rogamoore** [comment]
I think something went wrong during the composer command. Can you please
try again in a new folder starting with step 4 and check if there are any
errors?
You can also try dev-master as it is pretty stable.
Am 04.02.2016 6:39 nachm. schrieb "tipcircle" <notifications@github.com>:

**Comment by tipcircle** [comment]
I tried dev-master and all went very smooth. Thank you.
