### ISSUE TITLE
Google Analytics Help?

### ISSUE THREAD

**Issue by sizzly** [CampaignChain/campaignchain-ce#25]
Greetings!  I was finally able to get this fun software installed and I'm totally digging it.  However, I'm having some issues with the Google Analytics integration.

When I click on "Connect With Google" it prompts for an ID and password as one would expect but then it tells me that the redirect_uri is invalid.  

I'm sure I'm doing something wrong in the configuration of the key so if anyone has a step by step for how to make it work that'd be grand.

Thanks!

**Comment by ghostika** [comment]
Hello @sizzly,
I suppose you already created an app in Google Console, but you have to enable the redirect url, what should be something like this:
`http://example.com/security/authentication/client/oauth/login?hauth.done=Google`

Can you please try this?

**Comment by sizzly** [comment]
Ugh.  I haven't had a chance to go back to this but I will!  And thanks tons for your quick response.
