### ISSUE TITLE
RuntimeException: spin.min.js does not exist

### ISSUE THREAD

**Issue by JordanKnott** [CampaignChain/campaignchain-ce#471]
When trying to install through composer, I get the following error:

```
[RuntimeException]
The source file "/var/www/html/app/../web/vendor/campaignchain/core/ladda/dist/spin.min.js" does not exist.
```

I'm building on Ubuntu Xenial 64

**Comment by ceic18** [comment]
fixed????

**Comment by siccl** [comment]
@ceic18 You need manual add file _ladda/dist/spin.min.js_ to continue, this file is from previous version of ladda, after that simple retry the command to setup
