### ISSUE TITLE
Delete Action for Channels missing

### ISSUE THREAD

**Issue by jkoenig** [CampaignChain/campaignchain-ce#5]
Once channel has been created it should be possible to delete it, e.g channels that has been created for testing purpose

**Comment by groganz** [comment]
That's a tricky one.

I'd rather "pause" a channel, which means that all past campaigns and activities that made use of a channel would still be intact. For ongoing or upcoming campaigns/activities, pausing a channel would mean that all activities using that channel would also be paused.

Having paused a channel would mean that you cannot create new activities for a location that resides within that channel.

Does that make sense?

**Comment by rogamoore** [comment]
Is this resolved?

**Comment by groganz** [comment]
@tico86 ?

**Comment by tico86** [comment]
Yes this is resolved.
