### ISSUE TITLE
CTA javascript code prevents onClick events

### ISSUE THREAD

**Issue by jkoenig** [CampaignChain/campaignchain-ce#7]
This code prevents existing onClick functions to be executed aftewards

`
// Has a link been clicked?
    jQuery('a').click(function(){
        campaignchain.sendUrlReport(jQuery(this).attr("href"));
        return false;
    })`

**Comment by groganz** [comment]
Try to change the mode at https://github.com/CampaignChain/core/blob/master/Resources/public/js/campaignchain/campaignchain_tracking.js#L109. The way it should work that if the mode is "prod", then clicks should work properly.

**Comment by jkoenig** [comment]
We are currently running in 'prod' mode :(

**Comment by groganz** [comment]
Fixed with https://github.com/CampaignChain/core/commit/d60f8a6726fb49995ee109818e3b1fe19c60d021#diff-75d218faeb4a239aa435095b53b1a280R179

**Comment by sizzly** [comment]
I'm having this issue with the current beta version I installed on Feb 15th.  I'm using a bootstrap theme.
