### ISSUE TITLE
Create new user action missing

### ISSUE THREAD

**Issue by jkoenig** [CampaignChain/campaignchain-ce#8]
It should be possible to add, remove and modify users of campaign chain.

**Comment by groganz** [comment]
I'd suggest to implement that by using the Sonata user management and integrating it with CampaignChain. I like the way how https://www.mautic.org/ did it, i.e. as part of a vertical navigation on the right hand side that slides in when you click the settings icon.

**Comment by groganz** [comment]
https://campaignchain.atlassian.net/browse/CE-390?jql=text%20~%20%22user%22
